# -*- coding: utf-8 -*-
"""Paule_CSIS324LA_FEATUREEXTRACTIONANDREPRESENTATION

Automatically generated by Colab.

# Paule_CSIS324LA_FEATUREEXTRACTIONANDREPRESENTATION
## Faith Moselle O. Paule
## BCS35
## Due: Apr 21
## CSIS324LA Finals
  EA: MODULE 7 – FEATURE EXTRACTION AND REPRESENTATION - 50 points

#Task 1: Feature Extraction using VGG16
DESCRIPTION: You are performing Feature Extraction using a pre-trained Convolutional Neural Network (VGG16) as part of a module on Feature Extraction and Representation in Computer Vision. The goal is to convert an image into a numerical "fingerprint" (feature vector) that a machine learning model can use for tasks like classification or comparison.
TOPIC: Computer Vision

Programming Language: Python 3
- Tech Stack:
- TensorFlow / Keras: To load the pre-trained VGG16 model.
- NumPy: For numerical operations on the feature vectors.
- Google Colab: The development environment (as seen in the file header).

"""

# Import necessary libraries
from tensorflow.keras.applications.vgg16 import VGG16, preprocess_input
from tensorflow.keras.preprocessing import image
import numpy as np

# 1. Load the pre-trained VGG16 model without the final classification layer
#    'include_top=False' means the model outputs feature maps, not a class label.
print("Loading VGG16 model...")
model = VGG16(weights='imagenet', include_top=False)
print("Model loaded successfully.")

# 2. Load and prepare a sample image ('lego.png')
#    The image is resized to 224x224, the standard input size for VGG16.
img_path = 'lego.png' # Replace with your image path
img = image.load_img(img_path, target_size=(224, 224))

# 3. Convert the image to a numpy array and add a batch dimension
x = image.img_to_array(img)       # Shape: (224, 224, 3)
x = np.expand_dims(x, axis=0)     # Shape: (1, 224, 224, 3)

# 4. Preprocess the image for the VGG16 model (e.g., converts BGR to RGB, subtracts mean)
x = preprocess_input(x)

# 5. Extract features using the VGG16 model
#    The model's output is a feature map representing the presence of different patterns.
features = model.predict(x)       # Output shape: (1, 7, 7, 512)

# 6. Flatten the feature map into a 1D vector to serve as the image's "fingerprint"
features_flat = features.flatten()

# 7. Print the results
print("\n--- Feature Extraction Results ---")
print(f"Number of features extracted: {len(features_flat)}")
print(f"First 10 feature values: {features_flat[:10]}")
print("\nNote: These numbers represent the activation strengths of various learned")
print("      feature detectors (e.g., edges, textures, shapes) in the image.")
