# -*- coding: utf-8 -*-
"""Paule_SA_CSIS324LA - Summative Assessment: Image Processing Techniques

Automatically generated by Colab.

AUTHOR: Faith Paule
PROGRAM CODE: BCS35
COURSE: CSIS324LA
DUE DATE: Mar 13, 11:59 am

ASSESSMENT TYPE: Summative Assessment
TOPIC: Computer Vision / Image Processing - Spatial Filtering (Gaussian, Mean), Geometric Transformations
TASKS A summative assessment in image processing applying three fundamental techniques:
1. Gaussian Filtering - Noise reduction and smoothing
2. Mean Filtering - Pixelation reduction
3. Geometric Transformation (Rotation) - Orientation correction

Programming Language: Python 3

Tech Stack:
- OpenCV (cv2) - Gaussian blur, mean blur, rotation, image I/O
- NumPy - Array operations (implicit)
- Matplotlib - Image display and visualization
- Google Colab - Jupyter notebook environment
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt


# ============================================================================
# TASK 1: GAUSSIAN FILTERING
# ============================================================================
print("=" * 60)
print("TASK 1: Gaussian Filtering")
print("=" * 60)

# Load personal profile photo
personal_photo = cv2.imread('profile.jpg')
if personal_photo is None:
    raise ValueError("Error: Personal photo not found. Check the file path.")

# Convert from BGR (OpenCV default) to RGB (matplotlib display)
personal_photo_rgb = cv2.cvtColor(personal_photo, cv2.COLOR_BGR2RGB)

# Apply Gaussian Blur (15x15 kernel, sigma=0 automatically calculated)
# Gaussian blur uses weighted average based on normal distribution
gaussian_blur = cv2.GaussianBlur(personal_photo_rgb, (15, 15), 0)

# Display original vs filtered side by side
plt.figure(figsize=(10, 5))

plt.subplot(1, 2, 1)
plt.imshow(personal_photo_rgb)
plt.title('Original Photo')
plt.axis('off')

plt.subplot(1, 2, 2)
plt.imshow(gaussian_blur)
plt.title('After Gaussian Filtering')
plt.axis('off')

plt.show()

print("\nExplanation:")
print("I chose a square-sized photo of myself because it had visible noise and uneven lighting.")
print("Applying Gaussian Filtering helped smooth out the noise and made the image appear cleaner and more visually appealing.")
print("✓ Gaussian blur preserves edges better than mean filtering due to weighted averaging.")

# ============================================================================
# TASK 2: MEAN FILTERING
# ============================================================================
print("\n" + "=" * 60)
print("TASK 2: Mean Filtering (Averaging)")
print("=" * 60)

# Load photo for mean filtering (Makati/car image)
mean_filter_photo = cv2.imread('makati.jpg')
if mean_filter_photo is None:
    raise ValueError("Error: Photo for mean filtering not found. Check the file path.")

# Convert to RGB
mean_filter_photo_rgb = cv2.cvtColor(mean_filter_photo, cv2.COLOR_BGR2RGB)

# Apply Mean Filter (Averaging) with 15x15 kernel
# Each output pixel is the average of all pixels in the kernel window
mean_filter = cv2.blur(mean_filter_photo_rgb, (15, 15))

# Display original vs filtered
plt.figure(figsize=(10, 5))

plt.subplot(1, 2, 1)
plt.imshow(mean_filter_photo_rgb)
plt.title('Original Photo')
plt.axis('off')

plt.subplot(1, 2, 2)
plt.imshow(mean_filter)
plt.title('After Mean Filtering')
plt.axis('off')

plt.show()

print("\nTask 2 Explanation:")
print("I chose a photo of a car that had noticeable pixelation and rough edges due to resizing.")
print("Applying Mean Filtering helped reduce the pixelation by smoothing out the image and making the details look more natural.")
print("✓ Mean filtering replaces each pixel with the average of its neighbors (simple but effective).")

# ============================================================================
# TASK 3: GEOMETRIC TRANSFORMATION (ROTATION)
# ============================================================================
print("\n" + "=" * 60)
print("TASK 3: Geometric Transformation (90° Rotation)")
print("=" * 60)

# Load photo for geometric transformation
geometric_photo = cv2.imread('food.jpg')
if geometric_photo is None:
    raise ValueError("Error: Photo for geometric transformation not found. Check the file path.")

# Convert to RGB
geometric_photo_rgb = cv2.cvtColor(geometric_photo, cv2.COLOR_BGR2RGB)

# Rotate the image by 90 degrees clockwise
height, width = geometric_photo_rgb.shape[:2]
center = (width // 2, height // 2)  # Center point for rotation

# Get rotation matrix (angle=90°, scale=1.0)
rotation_matrix = cv2.getRotationMatrix2D(center, 90, 1.0)

# Apply affine transformation
rotated_image = cv2.warpAffine(geometric_photo_rgb, rotation_matrix, (width, height))

# Display original vs rotated
plt.figure(figsize=(10, 5))

plt.subplot(1, 2, 1)
plt.imshow(geometric_photo_rgb)
plt.title('Original Photo')
plt.axis('off')

plt.subplot(1, 2, 2)
plt.imshow(rotated_image)
plt.title('After Geometric Transformation (90° Rotation)')
plt.axis('off')

plt.show()

print("\nTask 3 Explanation:")
print("I chose a photo of a burger that appeared slightly tilted and off-center.")
print("Using geometric transformations (rotation and translation) helped correct the orientation of the photo, making it look more visually pleasing and properly aligned.")
print("✓ Rotation is an affine transformation that preserves parallel lines and ratios of distances.")

# ============================================================================
# SUMMARY
# ============================================================================
print("\n" + "=" * 60)
print("ASSESSMENT SUMMARY")
print("=" * 60)
print("Completed Tasks:")
print("  ✅ Task 1: Gaussian Filtering (profile.jpg) - Noise reduction")
print("  ✅ Task 2: Mean Filtering (makati.jpg) - Pixelation reduction")
print("  ✅ Task 3: Geometric Transformation (food.jpg) - 90° rotation")
print("\nAll images processed successfully!")
