# -*- coding: utf-8 -*-
"""CSIS324LA_EA_LlameraMarticioPaule - Image Processing: Color Models, Interpolation, Geometric Transformations

Automatically generated by Colab.

COURSE: CSIS324LA
SECTION: BCS35

GROUP MEMBERS:
1. Llamera, Josh
2. Marticio, Viktor
3. Paule, Faith

ENABLING ACTIVITY 3: Image Processing Fundamentals
TOPIC: Computer Vision / Image Processing - Color Models, Interpolation, Geometric Transformations
DEFINITION:
- Task 1: Pixel Representation and Color Models (RGB and HSV) - loading and displaying images in both color spaces
- Task 2: Image Interpolation Methods (Nearest Neighbor, Bilinear, Bicubic) - comparing resizing techniques
- Task 3: Geometric Transformations (Scaling, Rotation, Translation) - applying affine transformations
- Task 4: Combined Pipeline (HSV + Bicubic + 30° Rotation + 50px Translation) - converting to HSV, scaling with bicubic, rotating 30°, translating 50px

Programming Language: Python 3

Libraries:
- OpenCV (cv2) - Image I/O, color conversion, resizing, affine transformations
- NumPy - Matrix operations, translation matrices
- Matplotlib - Image display and visualization
- Google Colab - Jupyter notebook environment
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# ============================================================================
# TASK 1: PIXEL REPRESENTATION AND COLOR MODELS (RGB & HSV)
# ============================================================================
print("=" * 60)
print("TASK 1: RGB and HSV Color Models")
print("=" * 60)

# Load image (OpenCV loads as BGR by default)
image = cv2.imread('image.jpg')

# Check if image loaded successfully
if image is None:
    raise ValueError("Error: Image not found. Check the file path.")

# Convert BGR to RGB (for matplotlib display)
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Convert BGR to HSV (Hue, Saturation, Value)
image_hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)

# Display all three color representations
plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
plt.imshow(image_rgb)
plt.title('RGB Image')
plt.axis('off')

plt.subplot(1, 3, 2)
plt.imshow(image_hsv)
plt.title('HSV Image')
plt.axis('off')

plt.subplot(1, 3, 3)
plt.imshow(image_rgb)  # Original in RGB format
plt.title('Original Image (RGB)')
plt.axis('off')

plt.suptitle('RGB vs HSV Color Models')
plt.show()

print("✓ RGB: Red, Green, Blue channels (additive color model)")
print("✓ HSV: Hue (color), Saturation (intensity), Value (brightness)")
print("  - More aligned with human perception of color")

# ============================================================================
# TASK 2: IMAGE INTERPOLATION METHODS
# ============================================================================
print("\n" + "=" * 60)
print("TASK 2: Image Interpolation Methods")
print("=" * 60)
print("Interpolation methods for image resizing:")
print("  - Nearest Neighbor: Fastest, blocky results")
print("  - Bilinear: Smoother, weighted average of 4 neighbors")
print("  - Bicubic: Slowest, sharpest, uses 16 neighbors")

methods = {
    "Nearest Neighbor": cv2.INTER_NEAREST,
    "Bilinear": cv2.INTER_LINEAR,
    "Bicubic": cv2.INTER_CUBIC
}
new_size = (400, 400)

plt.figure(figsize=(15, 5))
for idx, (method_name, method) in enumerate(methods.items(), 1):
    resized_image = cv2.resize(image, new_size, interpolation=method)
    
    plt.subplot(1, 3, idx)
    plt.imshow(cv2.cvtColor(resized_image, cv2.COLOR_BGR2RGB))
    plt.title(f"{method_name} Interpolation")
    plt.axis('off')

plt.suptitle('Comparison of Interpolation Methods')
plt.show()

# ============================================================================
# TASK 3: GEOMETRIC TRANSFORMATIONS
# ============================================================================
print("\n" + "=" * 60)
print("TASK 3: Geometric Transformations")
print("=" * 60)
print("  - Scaling: 50% reduction")
print("  - Rotation: 45 degrees")
print("  - Translation: +100 pixels (x, y)")

# ----- 3.1 SCALING (50% reduction) -----
scale_percent = 50
width = int(image.shape[1] * scale_percent / 100)
height = int(image.shape[0] * scale_percent / 100)
dim = (width, height)
rescaled_image = cv2.resize(image, dim)

# ----- 3.2 ROTATION (45 degrees) -----
center = (image.shape[1] // 2, image.shape[0] // 2)
rotation_matrix = cv2.getRotationMatrix2D(center, 45, 1.0)
rotated_image = cv2.warpAffine(image, rotation_matrix, (image.shape[1], image.shape[0]))

# ----- 3.3 TRANSLATION (shift by 100 pixels) -----
translation_matrix = np.float32([[1, 0, 100], [0, 1, 100]])
translated_image = cv2.warpAffine(image, translation_matrix, (image.shape[1], image.shape[0]))

# Display transformations
plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
plt.imshow(cv2.cvtColor(rescaled_image, cv2.COLOR_BGR2RGB))
plt.title('Scaled (50%)')
plt.axis('off')

plt.subplot(1, 3, 2)
plt.imshow(cv2.cvtColor(rotated_image, cv2.COLOR_BGR2RGB))
plt.title('Rotated (45°)')
plt.axis('off')

plt.subplot(1, 3, 3)
plt.imshow(cv2.cvtColor(translated_image, cv2.COLOR_BGR2RGB))
plt.title('Translated (+100px)')
plt.axis('off')

plt.suptitle('Geometric Transformations')
plt.show()

# ============================================================================
# TASK 4: COMBINE CONCEPTS (HSV + Bicubic + Rotation + Translation)
# ============================================================================
print("\n" + "=" * 60)
print("TASK 4: Combined Image Manipulation Pipeline")
print("=" * 60)
print("Pipeline steps:")
print("  1. Convert to HSV color model")
print("  2. Scale using Bicubic interpolation (50%)")
print("  3. Rotate by 30 degrees")
print("  4. Translate by 50 pixels (x, y)")

# Step 1: Convert to HSV
image_hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)

# Step 2: Scale with Bicubic interpolation
scaled_hsv = cv2.resize(image_hsv, dim, interpolation=cv2.INTER_CUBIC)

# Step 3: Rotate by 30 degrees
center_hsv = (scaled_hsv.shape[1] // 2, scaled_hsv.shape[0] // 2)
rotation_matrix_30 = cv2.getRotationMatrix2D(center_hsv, 30, 1.0)
rotated_hsv = cv2.warpAffine(scaled_hsv, rotation_matrix_30, (scaled_hsv.shape[1], scaled_hsv.shape[0]))

# Step 4: Translate by 50 pixels
translation_matrix_50 = np.float32([[1, 0, 50], [0, 1, 50]])
translated_hsv = cv2.warpAffine(rotated_hsv, translation_matrix_50, (rotated_hsv.shape[1], rotated_hsv.shape[0]))

# Convert HSV back to RGB for display
final_image = cv2.cvtColor(translated_hsv, cv2.COLOR_HSV2RGB)

plt.figure(figsize=(8, 8))
plt.imshow(final_image)
plt.title('Final Image: HSV + Bicubic + 30° Rotation + 50px Translation')
plt.axis('off')
plt.show()

print("\n✓ Combined transformation completed successfully!")

# ============================================================================
# ANALYSIS QUESTIONS
# ============================================================================
print("\n" + "=" * 60)
print("ANALYSIS QUESTIONS")
print("=" * 60)

print("""
1. The image is converted to the HSV color model.
   ✓ TRUE.
   Explanation: The HSV color model represents colors in terms of Hue, 
   Saturation, and Value, which makes it more aligned with human perception. 
   Converting an image to HSV allows for easier manipulation of color properties.

2. Bicubic interpolation is applied for resizing.
   ✓ TRUE.
   Explanation: Bicubic interpolation uses the closest 16 pixels to determine 
   new pixel values, resulting in sharper and higher-quality resized images 
   compared to nearest-neighbor or bilinear interpolation.

3. The image is rotated and translated using the same geometric transformations.
   ✓ TRUE.
   Explanation: Rotation and translation are both rigid transformations, 
   meaning they preserve the shape and size of the object while altering its 
   position or orientation.
""")
