# -*- coding: utf-8 -*-
"""Paule_CSIS324LA_ImageSegmentation - Region Analysis and Contour Following

Automatically generated by Colab.

AUTHOR: Faith Moselle O. Paule
PROGRAM: BCS35
COURSE: CSIS324LA (Finals)
DUE DATE: Apr 12

ACTIVITY: EA - Region Analysis and Contour Following (50 points)

TOPIC: Computer Vision / Image Processing laboratory activity focusing on Region Analysis and Contour Following
IDENTIFICATION: The tasks involve implementing and comparing three core image segmentation techniques:
- Thresholding (Global Otsu vs. Local Adaptive)
- Edge Detection (Canny algorithm)
- Region-based Segmentation (Connected Components analysis)

Programming Language: Python 3

Tech Stack:
- OpenCV (cv2): For thresholding, edge detection (Canny), and connected components.
- Matplotlib: For displaying images and results.
- NumPy: For array operations.
- Google Colab: The environment, with a fix (cv2_imshow) for displaying images.
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab.patches import cv2_imshow # For image display in Colab


# ============================================================================
# TASK 1: GLOBAL vs LOCAL THRESHOLDING
# ============================================================================
def thresholding_demo(image_path):
    """
    Compares Otsu's (global) thresholding and Adaptive (local) thresholding.
    Displays original, Otsu, and Adaptive results side-by-side.
    """
    # Load image in grayscale
    img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    if img is None:
        print(f"Error: Could not load image from {image_path}")
        return

    # Global Thresholding (Otsu's Method - automatically calculates one threshold)
    _, global_thresh = cv2.threshold(img, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)

    # Local Adaptive Thresholding (threshold varies by local pixel neighborhood)
    # Uses the mean of an 11x11 block, subtracts a constant (2)
    local_thresh = cv2.adaptiveThreshold(img, 255, cv2.ADAPTIVE_THRESH_MEAN_C,
                                         cv2.THRESH_BINARY, 11, 2)

    # Display results
    titles = ['Original (Grayscale)', 'Global (Otsu)', 'Local (Adaptive)']
    images = [img, global_thresh, local_thresh]

    plt.figure(figsize=(12, 4))
    for i in range(3):
        plt.subplot(1, 3, i+1)
        plt.imshow(images[i], cmap='gray')
        plt.title(titles[i])
        plt.axis('off')
    plt.tight_layout()
    plt.show()


# ============================================================================
# TASK 2: EDGE DETECTION (CANNY)
# ============================================================================
def edge_segmentation(image_path):
    """
    Applies Canny edge detection to an image.
    Displays the original and the resulting edge map.
    """
    # Load original color image
    img = cv2.imread(image_path, cv2.IMREAD_COLOR)
    if img is None:
        print(f"Error: Could not load image from {image_path}")
        return

    # Convert to grayscale (edges are detected on intensity)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Apply Canny edge detector (thresholds: 100 and 200)
    edges = cv2.Canny(gray, 100, 200)

    # Display using Colab-compatible functions
    print("Original Image:")
    cv2_imshow(img)
    print("\nEdge Segmentation Result (White pixels are edges):")
    cv2_imshow(edges)


# ============================================================================
# TASK 3: REGION-BASED SEGMENTATION (CONNECTED COMPONENTS)
# ============================================================================
def region_based_segmentation(image_path):
    """
    Segments an image using binary thresholding and connected components.
    Displays a color-coded map of the detected regions.
    """
    # Load image in grayscale
    img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    if img is None:
        print(f"Error: Could not load image from {image_path}")
        return

    # Create a binary image using a simple threshold (127)
    _, binary = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY)

    # Find connected components (blobs of white pixels)
    # num_labels includes the background (label 0)
    num_labels, labels = cv2.connectedComponents(binary)

    # Display the result, color-coding each region
    # Subtract 1 from num_labels to exclude the background
    plt.figure(figsize=(8, 6))
    plt.imshow(labels, cmap='jet')
    plt.title(f'Segmented Regions ({num_labels - 1} foreground regions)', fontsize=14)
    plt.axis('off')
    plt.colorbar(label='Region ID')
    plt.tight_layout()
    plt.show()


# ============================================================================
# MAIN EXECUTION FOR THE ACTIVITY
# ============================================================================
if __name__ == "__main__":
    # Define the path to your image file (uploaded to Colab)
    image_file = 'computer.png' # Replace with your actual filename

    print("="*50, "\nTASK 1: Thresholding Comparison\n" + "="*50)
    thresholding_demo(image_file)

    print("\n" + "="*50, "\nTASK 2: Edge Detection\n" + "="*50)
    edge_segmentation(image_file)

    print("\n" + "="*50, "\nTASK 3: Region-based Segmentation\n" + "="*50)
    region_based_segmentation(image_file)
