# -*- coding: utf-8 -*-
"""Paule_CSIS324LA_ImageSegmentation - Laboratory Activity: Image Segmentation Techniques

Automatically generated by Colab.

AUTHOR: Faith Paule
PROGRAM CODE: BCS35
COURSE: CSIS324LA (Finals)
DUE DATE: Apr 2

ASSIGNMENT: EA - Image Segmentation Laboratory Activity (50 points)

TOPIC: Computer Vision / Image Processing - Image Segmentation, Thresholding, Edge Detection, Connected Components
TASKS An image segmentation laboratory activity implementing three core techniques:
1. Global vs Local Thresholding (Otsu + Adaptive Threshold)
2. Edge Detection (Canny Edge Detector)
3. Region-based Segmentation (Connected Components)
4. Reflection Questions

Programming Language: Python 3

Tech Stack:
- OpenCV (cv2) - Thresholding, edge detection (Canny), connected components
- NumPy - Array operations
- Matplotlib - Image display and visualization
- Google Colab - Jupyter notebook environment
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt


# ============================================================================
# TASK 1: GLOBAL AND LOCAL THRESHOLDING
# ============================================================================
print("=" * 60)
print("TASK 1: Global vs Local Thresholding")
print("=" * 60)

def thresholding_demo(image_path):
    """
    Compare global (Otsu) and local (adaptive) thresholding.
    
    Global Thresholding (Otsu):
    - Single threshold value for entire image
    - Best for uniform lighting conditions
    
    Local Thresholding (Adaptive):
    - Different thresholds for different regions
    - Better for uneven lighting
    """
    # Load image in grayscale
    image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    if image is None:
        print("Error: Could not read image.")
        return
    
    # Global Thresholding using Otsu's method
    # Automatically computes optimal threshold value
    _, global_thresh = cv2.threshold(image, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
    
    # Local (Adaptive) Thresholding
    # Uses mean of 11x11 neighborhood, C=2 constant subtracted
    local_thresh = cv2.adaptiveThreshold(
        image, 255, cv2.ADAPTIVE_THRESH_MEAN_C, 
        cv2.THRESH_BINARY, 11, 2
    )
    
    # Display results side by side
    titles = ['Original Image', 'Global Thresholding (Otsu)', 'Local (Adaptive) Thresholding']
    images = [image, global_thresh, local_thresh]
    
    plt.figure(figsize=(15, 5))
    for i in range(3):
        plt.subplot(1, 3, i + 1)
        plt.imshow(images[i], cmap='gray')
        plt.title(titles[i])
        plt.axis('off')
    
    plt.suptitle('Thresholding Comparison: Global vs Local', fontsize=14)
    plt.tight_layout()
    plt.show()
    
    return global_thresh, local_thresh

# Execute Task 1 (replace with actual image path)
# thresholding_demo('image.jpg')


# ============================================================================
# TASK 2: EDGE DETECTION (Canny Edge Detector)
# ============================================================================
print("\n" + "=" * 60)
print("TASK 2: Edge Detection using Canny Algorithm")
print("=" * 60)

def edge_segmentation(image_path):
    """
    Detect edges using Canny edge detector.
    
    Canny Algorithm Steps:
    1. Gaussian blur to reduce noise
    2. Gradient calculation (Sobel)
    3. Non-maximum suppression
    4. Hysteresis thresholding (minVal=100, maxVal=200)
    
    NOTE: In Google Colab, use matplotlib instead of cv2.imshow()
    """
    # Load image in color and grayscale
    image = cv2.imread(image_path, cv2.IMREAD_COLOR)
    if image is None:
        print("Error: Could not read image.")
        return
    
    # Convert to grayscale (edges detected on intensity)
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    
    # Apply Canny Edge Detection
    # minVal=100, maxVal=200 (edges between these thresholds are kept)
    edges = cv2.Canny(gray, 100, 200)
    
    # Convert BGR to RGB for proper matplotlib display
    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    
    # Display using matplotlib (works in Colab)
    plt.figure(figsize=(12, 5))
    
    plt.subplot(1, 2, 1)
    plt.imshow(image_rgb)
    plt.title('Original Image')
    plt.axis('off')
    
    plt.subplot(1, 2, 2)
    plt.imshow(edges, cmap='gray')
    plt.title('Edge Segmentation (Canny)')
    plt.axis('off')
    
    plt.suptitle('Edge Detection Results', fontsize=14)
    plt.show()
    
    return edges

# Execute Task 2 (replace with actual image path)
# edge_segmentation('image.jpg')


# ============================================================================
# TASK 3: REGION-BASED SEGMENTATION (Connected Components)
# ============================================================================
print("\n" + "=" * 60)
print("TASK 3: Region-based Segmentation (Connected Components)")
print("=" * 60)

def region_based_segmentation(image_path):
    """
    Segment image using connected components analysis.
    
    Steps:
    1. Threshold image to binary
    2. Find connected components (contiguous regions of white pixels)
    3. Color-code each region uniquely using 'jet' colormap
    
    Output: Color-coded regions with count in title
    """
    # Load image in grayscale
    image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    if image is None:
        print("Error: Could not read image.")
        return
    
    # Binary thresholding (pixels > 127 become white)
    _, binary = cv2.threshold(image, 127, 255, cv2.THRESH_BINARY)
    
    # Find connected components
    # num_labels = number of regions (including background)
    # labels = matrix where each pixel has region ID
    num_labels, labels = cv2.connectedComponents(binary)
    
    # Subtract 1 to exclude background from region count
    print(f"Detected regions: {num_labels - 1} (excluding background)")
    
    # Display color-coded regions using 'jet' colormap
    plt.figure(figsize=(8, 6))
    plt.imshow(labels, cmap='jet')
    plt.title(f'Segmented Regions ({num_labels - 1} regions)', fontsize=14)
    plt.axis('off')
    plt.colorbar(label='Region ID')
    plt.tight_layout()
    plt.show()
    
    return labels, num_labels

# Execute Task 3 (replace with actual image path)
# region_based_segmentation('image.jpg')


# ============================================================================
# TASK 4: REFLECTION QUESTIONS
# ============================================================================
print("\n" + "=" * 60)
print("TASK 4: Reflection")
print("=" * 60)

print("""
1. ERRORS IDENTIFIED AND CORRECTIONS:
   ─────────────────────────────────────────────────────────────────
   
   Task 1 (Thresholding):
   • ERROR: None - code was functional
   • ENHANCEMENT: Added error handling for missing image file
   • ENHANCEMENT: Added better titles and figure formatting
   
   Task 2 (Edge Detection):
   • ERROR: cv2.imshow() does not work in Google Colab
   • FIX: Replaced with matplotlib's plt.imshow() for Colab compatibility
   • ENHANCEMENT: Converted BGR to RGB for correct color display
   
   Task 3 (Region Segmentation):
   • ERROR: Count displayed includes background (label 0)
   • FIX: Subtract 1 from num_labels for accurate region count
   • ENHANCEMENT: Added colorbar for region identification

2. LOCAL vs GLOBAL THRESHOLDING COMPARISON:
   ─────────────────────────────────────────────────────────────────
   
   GLOBAL THRESHOLDING:
   ───────────────────
   Uses a SINGLE threshold value for the entire image.
   Best for: Images with uniform lighting conditions.
   
   Real-life examples:
   1. Document scanning (white paper, black text - uniform background)
   2. Barcode reading (consistent lighting in controlled environment)
   
   LOCAL (ADAPTIVE) THRESHOLDING:
   ─────────────────────────────
   Uses DIFFERENT threshold values for different image regions.
   Best for: Images with uneven lighting or shadows.
   
   Real-life examples:
   1. License plate recognition (varying shadows, reflections)
   2. Handwritten document digitization (uneven lighting across page)

3. REGION-BASED vs EDGE SEGMENTATION:
   ─────────────────────────────────────────────────────────────────
   
   Which is better? It DEPENDS on the application!
   
   REGION-BASED SEGMENTATION is better when:
   • Need to identify COMPLETE OBJECTS (not just boundaries)
   • Objects have uniform color/intensity
   • Need to COUNT distinct objects (cells, products, etc.)
   • Example: Counting cells in medical imaging
   
   EDGE SEGMENTATION (Canny) is better when:
   • Need precise BOUNDARY detection
   • Objects have strong contrast with background
   • Need to find SHAPES and CONTOURS
   • Example: Lane detection for autonomous vehicles
   
   MY CONCLUSION:
   Region-based segmentation is generally more useful for 
   computer vision tasks because it provides object-level 
   understanding (complete regions with labels), while edge 
   detection is more suitable as a preprocessing step for 
   shape analysis or when only boundaries matter.
""")

print("\n" + "=" * 60)
print("LABORATORY ACTIVITY COMPLETED SUCCESSFULLY")
print("=" * 60)
