# -*- coding: utf-8 -*-
"""Paule_CSIS324LA_ImageEnhancement - Laboratory Activity: Image Enhancement Techniques

Automatically generated by Colab.

AUTHOR: Faith Paule
PROGRAM CODE: BCS35
COURSE: CSIS324LA (Finals)
DUE DATE: Apr 2

ASSIGNMENT: EA - Image Enhancement Laboratory Activity (50 points)

TOPIC: Computer Vision / Image Processing - Image Enhancement, Histogram Equalization, Adaptive Filtering (Wiener)
TASKS:
1. Contrast Enhancement (Histogram Equalization)
2. Histogram Equalization with Before/After Histograms
3. Adaptive Wiener Filter for Noise Reduction
4. Reflection Questions

Programming Language: Python 3

Tech Stack:
- OpenCV (cv2) - Image I/O, histogram equalization, histogram calculation
- Matplotlib - Image and histogram visualization
- SciPy - Wiener filter implementation (scipy.signal.wiener)
- NumPy - Array clipping and type conversion
- Google Colab - Jupyter notebook environment
"""

import cv2
import matplotlib.pyplot as plt
import numpy as np
from scipy.signal import wiener


# ============================================================================
# TASK 1: CONTRAST ENHANCEMENT (HISTOGRAM EQUALIZATION)
# ============================================================================
print("=" * 60)
print("TASK 1: Contrast Enhancement using Histogram Equalization")
print("=" * 60)

def enhance_contrast(image_path):
    """
    Enhance image contrast using histogram equalization.
    
    Error corrections applied:
    - Fixed indentation (code block alignment)
    - Corrected filename to 'input.png'
    - Added error handling for missing image
    """
    # Read image in grayscale
    img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    if img is None:
        print("Error: Could not read image.")
        return
    
    # Apply histogram equalization (spreads pixel intensities)
    enhanced_img = cv2.equalizeHist(img)
    
    # Display original vs enhanced images
    plt.figure(figsize=(10, 5))
    
    plt.subplot(1, 2, 1)
    plt.imshow(img, cmap='gray')
    plt.title('Original Image')
    plt.axis('off')
    
    plt.subplot(1, 2, 2)
    plt.imshow(enhanced_img, cmap='gray')
    plt.title('Enhanced Image (Histogram Equalization)')
    plt.axis('off')
    
    plt.show()
    return enhanced_img

# Execute Task 1
enhance_contrast("/content/input.png")


# ============================================================================
# TASK 2: HISTOGRAM EQUALIZATION WITH HISTOGRAM DISPLAY
# ============================================================================
print("\n" + "=" * 60)
print("TASK 2: Histogram Equalization with Before/After Histograms")
print("=" * 60)

def histogram_equalization(image_path):
    """
    Apply histogram equalization and display both images and their histograms.
    
    Error corrections applied:
    - Fixed indentation
    - Added plt.tight_layout() for better plot readability
    - Corrected filename to 'input.png'
    """
    # Read image in grayscale
    img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    if img is None:
        print("Error: Could not read image.")
        return
    
    # Apply histogram equalization
    enhanced_img = cv2.equalizeHist(img)
    
    # Compute histograms (pixel intensity distribution)
    original_hist = cv2.calcHist([img], [0], None, [256], [0, 256])
    enhanced_hist = cv2.calcHist([enhanced_img], [0], None, [256], [0, 256])
    
    # Display 2x2 grid: images top, histograms bottom
    plt.figure(figsize=(12, 6))
    
    # Top-Left: Original Image
    plt.subplot(2, 2, 1)
    plt.imshow(img, cmap='gray')
    plt.title('Original Image')
    plt.axis('off')
    
    # Top-Right: Enhanced Image
    plt.subplot(2, 2, 2)
    plt.imshow(enhanced_img, cmap='gray')
    plt.title('Enhanced Image')
    plt.axis('off')
    
    # Bottom-Left: Original Histogram
    plt.subplot(2, 2, 3)
    plt.plot(original_hist, color='black')
    plt.title('Original Histogram')
    plt.xlim([0, 256])
    plt.xlabel('Pixel Intensity')
    plt.ylabel('Frequency')
    
    # Bottom-Right: Enhanced Histogram
    plt.subplot(2, 2, 4)
    plt.plot(enhanced_hist, color='black')
    plt.title('Enhanced Histogram (Equalized)')
    plt.xlim([0, 256])
    plt.xlabel('Pixel Intensity')
    plt.ylabel('Frequency')
    
    plt.tight_layout()  # Improves spacing between subplots
    plt.show()

# Execute Task 2
histogram_equalization("/content/input.png")


# ============================================================================
# TASK 3: ADAPTIVE WIENER FILTER
# ============================================================================
print("\n" + "=" * 60)
print("TASK 3: Adaptive Wiener Filter for Noise Reduction")
print("=" * 60)

def adaptive_wiener_filter(image_path):
    """
    Apply Wiener filter for adaptive noise reduction.
    
    Error corrections applied:
    - Converted image to float32 before filtering (Wiener expects float)
    - Clipped filtered values to [0, 255] range
    - Converted back to uint8 for proper display
    - Added proper filename 'input.png'
    
    Wiener filter adapts to local image statistics:
    - Low noise areas: preserves original values
    - High noise areas: applies stronger smoothing
    """
    # Read image in grayscale
    img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    if img is None:
        print("Error: Could not read image.")
        return
    
    # Convert to float32 (Wiener filter requires float input)
    img_float = img.astype(np.float32)
    
    # Apply Wiener filter with 5x5 kernel
    # Filter adapts based on local variance
    wiener_filtered = wiener(img_float, (5, 5))
    
    # Clip values to valid range [0, 255] and convert back to uint8
    wiener_filtered = np.clip(wiener_filtered, 0, 255).astype(np.uint8)
    
    # Display original vs Wiener filtered images
    plt.figure(figsize=(10, 5))
    
    plt.subplot(1, 2, 1)
    plt.imshow(img, cmap='gray')
    plt.title('Original Image (with noise)')
    plt.axis('off')
    
    plt.subplot(1, 2, 2)
    plt.imshow(wiener_filtered, cmap='gray')
    plt.title('Wiener Filter Applied')
    plt.axis('off')
    
    plt.show()

# Execute Task 3
adaptive_wiener_filter("/content/input.png")


# ============================================================================
# TASK 4: REFLECTION QUESTIONS
# ============================================================================
print("\n" + "=" * 60)
print("TASK 4: Reflection")
print("=" * 60)

print("""
1. ERRORS IDENTIFIED AND CORRECTIONS:
   ─────────────────────────────────────────────────────────────────
   
   Task 1 (Contrast Enhancement):
   • ERROR: Incorrect indentation in the original code
   • ERROR: Filename mismatch
   • FIX: Fixed indentation and used 'input.png' as correct filename
   
   Task 2 (Histogram Equalization):
   • ERROR: Indentation needed correction
   • ERROR: Missing plt.tight_layout() for better plot readability
   • FIX: Corrected indentation and added tight_layout()
   
   Task 3 (Adaptive Wiener Filter):
   • ERROR: Wiener filter output not properly handled for display
   • FIX: Converted image to float32 before filtering
   • FIX: Clipped values between 0-255
   • FIX: Converted back to uint8 to prevent visualization issues

2. IMPORTANCE OF HISTOGRAMS IN IMAGE PROCESSING:
   ─────────────────────────────────────────────────────────────────
   
   A histogram provides a visual representation of pixel intensity 
   distribution, allowing for better contrast adjustments and enhancement 
   techniques, which are crucial for improving image clarity and detail.
   
   REAL-LIFE USAGE EXAMPLES:
   
   • PHOTOGRAPHY & GRAPHIC DESIGN:
     - Adobe Photoshop's "Levels" and "Curves" tools
     - Used by designers to adjust brightness and contrast
     - Essential for marketing materials and social media content
     - Relevant as a student leader handling publication materials
     
   • MEDICAL IMAGING:
     - X-ray enhancement for better diagnosis
     - MRI and CT scan contrast adjustment
     
   • SECURITY & SURVEILLANCE:
     - Facial recognition accuracy improvement
     - Low-light image enhancement for CCTV footage
     
   • AI & MACHINE LEARNING:
     - Image preprocessing for classification models
     - Data augmentation for training datasets

3. WIENER FILTER vs EARLIER FILTERS:
   ─────────────────────────────────────────────────────────────────
   
   MAIN DIFFERENCE: The Wiener filter is an ADAPTIVE filter that adjusts
   its parameters based on local image characteristics.
   
   COMPARISON:
   
   • Histogram Equalization (Tasks 1 & 2):
     - GLOBAL operation (applies same transformation to entire image)
     - Focuses on contrast improvement
     - Does NOT consider noise levels
     
   • Wiener Filter (Task 3):
     - LOCAL/ADAPTIVE operation (varies by region)
     - Focuses on noise reduction while preserving edges
     - Uses local mean and variance to adapt
     
   USE CASES FOR WIENER FILTER:
   - Medical imaging (preserves diagnostic details while reducing noise)
   - Low-light photography (removes sensor noise)
   - Satellite imagery (enhances features while suppressing noise)
""")

print("\n" + "=" * 60)
print("LABORATORY ACTIVITY COMPLETED SUCCESSFULLY")
print("=" * 60)
