# -*- coding: utf-8 -*-
"""Paule_CSIS324LA_Lab2 - Image Blurring and Quality Assessment

Automatically generated by Colab.

AUTHOR: Faith Paule
PROGRAM CODE: BCS35
COURSE: CSIS324LA

ASSIGNMENT: Lab 2 - Image Blurring and Quality Metrics
TOPIC: Computer Vision / Image Processing - Image Blurring, Spatial Filtering, Quality Assessment Metrics

DESCRIPTION: Implementing image blurring and quality assessment techniques including
- Apply average blur (mean filter) to an image using cv2.blur() with a 5×5 kernel
- Apply Gaussian blur using custom 3×3 kernel with cv2.filter2D()
- Compare quality using MSE, RMSE, PSNR, SSIM metrics comparing original and blurred images

Programming Language: Python 3

Tech Stack:
- OpenCV (cv2) - Image reading, blur operations, filter2D
- NumPy - Array operations, kernel creation
- Matplotlib - Image display, subplot visualization
- Scikit-image (skimage) - MSE, PSNR, RMSE, SSIM metrics
- SEWAR - Full-reference image quality assessment (installed)
- PIL (Pillow) - Image handling
- Google Colab - Jupyter notebook environment
"""

import cv2 as cv
import numpy as np
from matplotlib import pyplot as plt
from skimage import measure, metrics
from skimage.metrics import structural_similarity as ssim

# ============================================================================
# PART 1: AVERAGE BLUR (MEAN FILTER)
# ============================================================================
print("=" * 60)
print("PART 1: AVERAGE BLUR (5x5 kernel)")
print("=" * 60)

# Load the sneakers image
img = cv.imread('sneakers.png')
# Convert BGR to RGB for correct matplotlib display (OpenCV loads as BGR)
img_rgb = cv.cvtColor(img, cv.COLOR_BGR2RGB)

# Apply average blur with 5x5 kernel (all ones, divided by 25)
blur = cv.blur(img, (5, 5))
blur_rgb = cv.cvtColor(blur, cv.COLOR_BGR2RGB)

# Display original vs blurred side by side
plt.figure(figsize=(12, 5))
plt.subplot(121)
plt.imshow(img_rgb)
plt.title('Original')
plt.xticks([]), plt.yticks([])

plt.subplot(122)
plt.imshow(blur_rgb)
plt.title('Blurred (5x5 Average Filter)')
plt.xticks([]), plt.yticks([])
plt.show()

# ============================================================================
# PART 2: GAUSSIAN BLUR USING CUSTOM KERNEL
# ============================================================================
print("\n" + "=" * 60)
print("PART 2: GAUSSIAN BLUR (3x3 kernel, 1/25 weights)")
print("=" * 60)

# Create a simple 3x3 averaging kernel (approximates Gaussian)
gaussian_kernel = np.ones((3, 3), np.float32) / 25
print(f"Gaussian kernel:\n{gaussian_kernel}")

# Apply filter2D with custom kernel
conv_gaussian = cv.filter2D(img, -1, gaussian_kernel, borderType=cv.BORDER_CONSTANT)
conv_gaussian_rgb = cv.cvtColor(conv_gaussian, cv.COLOR_BGR2RGB)

plt.figure(figsize=(6, 6))
plt.imshow(conv_gaussian_rgb)
plt.title('Gaussian Blur (3x3 kernel)')
plt.xticks([]), plt.yticks([])
plt.show()

# ============================================================================
# PART 3: QUALITY METRICS COMPARISON
# ============================================================================
print("\n" + "=" * 60)
print("PART 3: IMAGE QUALITY METRICS")
print("=" * 60)
print("Metrics explanation:")
print("  - MSE (Mean Squared Error): Lower = more similar")
print("  - RMSE (Root Mean Squared Error): Lower = more similar")
print("  - PSNR (Peak Signal-to-Noise Ratio): Higher = better quality")
print("  - SSIM (Structural Similarity): 1 = identical images")
print("-" * 60)

# Load original and blurred images for comparison
orig = cv.imread('blur.png', 1)   # Original reference image
gauss = cv.imread('gauss.png', 1) # Gaussian blurred image

# Convert BGR to RGB for metrics (skimage expects RGB)
orig_rgb = cv.cvtColor(orig, cv.COLOR_BGR2RGB)
gauss_rgb = cv.cvtColor(gauss, cv.COLOR_BGR2RGB)

# 1. RMSE (Root Mean Squared Error)
rmse_skimg = metrics.normalized_root_mse(orig_rgb, gauss_rgb)
print(f"RMSE: {rmse_skimg:.4f}")

# 2. MSE (Mean Squared Error)
mse_skimg = metrics.mean_squared_error(orig_rgb, gauss_rgb)
print(f"MSE: {mse_skimg:.4f}")

# 3. PSNR (Peak Signal-to-Noise Ratio)
psnr_skimg = metrics.peak_signal_noise_ratio(orig_rgb, gauss_rgb, data_range=None)
print(f"PSNR: {psnr_skimg:.2f} dB")

# 4. SSIM (Structural Similarity Index)
# data_range = max pixel value - min pixel value (typically 255 - 0 = 255)
# multichannel = True for RGB images
data_range = orig_rgb.max() - orig_rgb.min()
ssim_skimg = ssim(orig_rgb, gauss_rgb, data_range=data_range, multichannel=True, win_size=3)
print(f"SSIM: {ssim_skimg:.4f}")

# ============================================================================
# METRICS INTERPRETATION
# ============================================================================
print("\n" + "=" * 60)
print("METRICS INTERPRETATION")
print("=" * 60)

if mse_skimg < 100:
    print("✓ MSE is low - images are very similar")
else:
    print("⚠ MSE is high - significant differences detected")

if psnr_skimg > 30:
    print("✓ PSNR > 30 dB - good quality retention")
else:
    print("⚠ PSNR < 30 dB - noticeable quality loss")

if ssim_skimg > 0.9:
    print("✓ SSIM > 0.9 - strong structural similarity")
else:
    print("⚠ SSIM < 0.9 - structural differences detected")
