# -*- coding: utf-8 -*-
"""Paule_CSIS324LA_Lab1 - Image Denoising Filters (Mean, Median, Adaptive, Alpha-Trimmed)

Automatically generated by Colab.

AUTHOR: Faith Paule
PROGRAM CODE: BCS35
COURSE: CSIS324LA

ASSIGNMENT: Week 1 & 2 - Mean Filter and Image Denoising
TOPIC: Computer Vision / Image Processing - Image Denoising, Spatial Filtering, Quality Metrics
DESCRIPTION:
Implementation and comparison of spatial domain filters:
1. Mean Filter (averaging)
2. Standard Median Filter
3. Adaptive Median Filter (kernel size varies)
4. Alpha-Trimmed Mean Filter (removes outliers)
5. The program also computes quality metrics (MSE, RMSE, PSNR, SSIM) to evaluate filter performance.

Programming Language: Python 3

Tech Stack:
- OpenCV (cv2) - Image reading, median blur, filter2D
- NumPy - Array operations, padding, image manipulation
- Matplotlib - Image display, histograms
- Scikit-image (skimage) - MSE, PSNR, RMSE, SSIM metrics
- SEWAR - Image quality assessment (installed but not used)
- PIL (Pillow) - Image handling
- Google Colab - Jupyter notebook environment

METRICS:
- MSE (Mean Squared Error)
- RMSE (Root Mean Squared Error)
- PSNR (Peak Signal-to-Noise Ratio)
- SSIM (Structural Similarity Index)
"""

import numpy as np
from matplotlib import pyplot as plt
import cv2
from skimage import metrics
from skimage.metrics import structural_similarity as ssim

# ============================================================================
# HELPER FUNCTIONS
# ============================================================================
def show(img):
    """Display grayscale image without axes ticks."""
    plt.imshow(img, cmap='gray')
    plt.xticks([])
    plt.yticks([])


def compute_metrics(original, filtered, name):
    """
    Compute and display image quality metrics.
    
    Args:
        original: Original reference image
        filtered: Filtered/denoised image
        name: Filter name for display
    """
    mse = metrics.mean_squared_error(original, filtered)
    psnr = metrics.peak_signal_noise_ratio(original, filtered)
    ssim_value = ssim(original, filtered, data_range=original.max() - original.min())
    
    print(f"{name} - MSE: {mse:.4f}, PSNR: {psnr:.2f} dB, SSIM: {ssim_value:.4f}")


# ============================================================================
# FILTER IMPLEMENTATIONS
# ============================================================================
def standard_median_filter(image, kernel_size=3):
    """
    Standard median filter using OpenCV.
    
    Replaces each pixel with median of neighboring pixels.
    Excellent for removing salt-and-pepper noise.
    
    Args:
        image: Input grayscale image
        kernel_size: Size of the kernel (must be odd)
    
    Returns:
        Filtered image
    """
    return cv2.medianBlur(image, kernel_size)


def adaptive_median_filter(image, max_kernel_size=7):
    """
    Adaptive median filter that dynamically adjusts kernel size.
    
    Algorithm:
    1. Start with 3x3 kernel
    2. Check if median is between min and max
    3. If not, increase kernel size (up to max_kernel_size)
    4. Apply median filter with appropriate kernel
    
    Args:
        image: Input grayscale image
        max_kernel_size: Maximum kernel size to try
    
    Returns:
        Filtered image
    """
    h, w = image.shape
    new_img = np.copy(image)
    
    for i in range(h):
        for j in range(w):
            k = 3  # Start with 3x3 kernel
            
            while k <= max_kernel_size:
                # Get region boundaries
                i_min = max(i - k // 2, 0)
                i_max = min(i + k // 2 + 1, h)
                j_min = max(j - k // 2, 0)
                j_max = min(j + k // 2 + 1, w)
                
                region = image[i_min:i_max, j_min:j_max]
                z_min = np.min(region)
                z_max = np.max(region)
                z_med = np.median(region)
                z_xy = image[i, j]
                
                # Check if median is a true signal (not noise)
                if z_min < z_med < z_max:
                    # Pixel is noise if outside [min, med] range
                    if z_min < z_xy < z_max:
                        new_img[i, j] = z_xy  # Keep original
                    else:
                        new_img[i, j] = z_med  # Use median
                    break
                else:
                    k += 2  # Increase kernel size
                    
    return new_img


def alpha_trimmed_mean_filter(image, kernel_size=3, d=2):
    """
    Alpha-trimmed mean filter.
    
    Removes d/2 smallest and d/2 largest values before averaging.
    Good for removing mixed noise (impulse + Gaussian).
    
    Args:
        image: Input grayscale image
        kernel_size: Size of the kernel (must be odd)
        d: Number of values to trim from each end
    
    Returns:
        Filtered image
    """
    h, w = image.shape
    pad_size = kernel_size // 2
    padded_img = np.pad(image, pad_size, mode='reflect')
    new_img = np.zeros_like(image)
    
    for i in range(h):
        for j in range(w):
            # Extract kernel region
            region = padded_img[i:i+kernel_size, j:j+kernel_size].flatten()
            sorted_region = np.sort(region)
            
            # Trim outliers from both ends
            if d < kernel_size ** 2:
                trimmed_region = sorted_region[d//2 : -d//2]
            else:
                trimmed_region = sorted_region
                
            new_img[i, j] = np.mean(trimmed_region)
    
    return new_img.astype(np.uint8)


# ============================================================================
# MAIN EXECUTION
# ============================================================================
print("=" * 60)
print("IMAGE DENOISING - FILTER COMPARISON")
print("=" * 60)

# Load original grayscale image
img_original = cv2.imread('sunflower.png', 0)
print(f"Original image shape: {img_original.shape}")
print(f"Pixel value range: [{img_original.min()}, {img_original.max()}]")

# ============================================================================
# PART 1: MEAN FILTER (Basic Averaging)
# ============================================================================
print("\n" + "-" * 40)
print("PART 1: MEAN FILTER (3x3 kernel)")
print("-" * 40)

# Display original image and histogram
plt.figure(figsize=(12, 4))
plt.subplot(131)
show(img_original)
plt.title("Original Image")

plt.subplot(132)
plt.hist(img_original.ravel(), 256, [0, 256])
plt.title("Histogram")

# Apply mean filter
mean_kernel = np.ones((3, 3), np.float32) / 25
conv_mean = cv2.filter2D(img_original, -1, mean_kernel, borderType=cv2.BORDER_CONSTANT)

plt.subplot(133)
show(conv_mean)
plt.title("Mean Filter (3x3)")
plt.show()

# ============================================================================
# PART 2: MEDIAN FILTERS COMPARISON
# ============================================================================
print("\n" + "-" * 40)
print("PART 2: MEDIAN FILTERS COMPARISON")
print("-" * 40)

# Apply different median filters
median_filtered = standard_median_filter(img_original, kernel_size=3)
adaptive_filtered = adaptive_median_filter(img_original, max_kernel_size=7)
alpha_trimmed_filtered = alpha_trimmed_mean_filter(img_original, kernel_size=3, d=2)

# Display results
plt.figure(figsize=(15, 5))
plt.subplot(141)
show(img_original)
plt.title("Original")

plt.subplot(142)
show(median_filtered)
plt.title("Standard Median (3x3)")

plt.subplot(143)
show(adaptive_filtered)
plt.title("Adaptive Median")

plt.subplot(144)
show(alpha_trimmed_filtered)
plt.title("Alpha-Trimmed Mean")
plt.show()

# ============================================================================
# PART 3: QUALITY METRICS COMPARISON
# ============================================================================
print("\n" + "-" * 40)
print("PART 3: QUALITY METRICS")
print("-" * 40)
print("Metrics explanation:")
print("  - MSE (Mean Squared Error): Lower is better")
print("  - PSNR (Peak Signal-to-Noise Ratio): Higher is better")
print("  - SSIM (Structural Similarity): Closer to 1 is better")
print("-" * 40)

compute_metrics(img_original, median_filtered, "Standard Median Filter")
compute_metrics(img_original, adaptive_filtered, "Adaptive Median Filter")
compute_metrics(img_original, alpha_trimmed_filtered, "Alpha-Trimmed Mean Filter")

# ============================================================================
# ADDITIONAL: Mean Filter Metrics
# ============================================================================
print("\n" + "-" * 40)
print("MEAN FILTER METRICS")
print("-" * 40)

mse_mean = metrics.mean_squared_error(img_original, conv_mean)
psnr_mean = metrics.peak_signal_noise_ratio(img_original, conv_mean)
ssim_mean = ssim(img_original, conv_mean, data_range=img_original.max() - img_original.min())

print(f"Mean Filter - MSE: {mse_mean:.4f}, PSNR: {psnr_mean:.2f} dB, SSIM: {ssim_mean:.4f}")

print("\n" + "=" * 60)
print("FILTER COMPARISON COMPLETE")
print("=" * 60)
