# -*- coding: utf-8 -*-
"""Paule_CSIS324LA_Lab1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17X0NxExmRxWeh5IWF9RSeEHZHPujt7Vz
"""

#Name: Faith Paule
#Program Code: BCS35
#CSIS324LA

#Week # 1 & 2 Mean Filter
import numpy as np #read the array of the image
from matplotlib import pyplot as plt #use to show the image
import cv2 #read the image

# Read the original grayscale image
img_original = cv2.imread('sunflower.png', 0)
plt.imshow(img_original)

# Convert the image to a NumPy array and display pixel values
pixel_original=np.array(img_original)
print(pixel_original)

# Display histogram of pixel intensity distribution
plt.hist(pixel_original.ravel(),256,[0,256])
plt.show()# ravel function is to flatten the array from 2 dimensional to multi-deminsional

# Function to display an image
img1=img_original
plt.imshow(img1,cmap='RdYlGn')

def show(img):
  plt.imshow(img,cmap='gray')
  plt.xticks([]),
  plt.yticks([])

# Padding the image to create a border effect
h, w = img_original.shape
img = np.zeros((h+160, w), np.uint8)
img[80:-80, :] = img_original
plt.figure(figsize=(15, 5))
plt.subplot(131)
show(img)

pixel_gray=np.array([img])
pixel_gray

# Display histogram after padding
plt.hist(img.ravel(),256,[0,256]);
plt.show()

pip install sewar

from sewar import full_ref
from skimage import measure, metrics

from PIL import Image
from google.colab.patches import cv2_imshow
mean_kernel = np.ones((3,3),np.float32)/25

conv_mean= cv2.filter2D(img,-1,mean_kernel, borderType=cv2.BORDER_CONSTANT)
plt.figure(figsize=(5, 5))
show(conv_mean)

"""
### Explanation of Metrics:
1. **Mean Squared Error (MSE)**:
   - Measures the average squared difference between the original and filtered images.
   - Lower MSE indicates a smaller error and higher similarity.

2. **Root Mean Squared Error (RMSE)**:
   - Square root of MSE, providing error measurement in the same units as the pixel values.
   - Easier to interpret compared to MSE.

3. **Peak Signal-to-Noise Ratio (PSNR)**:
   - Measures the ratio of the peak signal (max pixel value) to the noise present.
   - Higher PSNR indicates better quality (less noise and distortion).

4. **Structural Similarity Index (SSIM)**:
   - Measures structural similarity between images by comparing luminance, contrast, and structure.
   - SSIM values range from -1 to 1, with 1 indicating identical images.
"""

rmse_skimg = metrics.normalized_root_mse(img, conv_mean)
print("RMSE: based on scikit image = ", rmse_skimg)

mse_skimg = metrics.mean_squared_error(img, conv_mean)
print("MSE: based on scikit image = ", mse_skimg)

psnr_skimg = metrics.peak_signal_noise_ratio(img, conv_mean, data_range=None)
print("PSNR: based on scikit image = ", psnr_skimg)

from skimage.metrics import structural_similarity as ssim
ssim_skimg = ssim(img, conv_mean, data_range = img.max() - img.min(), multichannel = True)
print("SSIM: based on scikit image = ", ssim_skimg)

import numpy as np
from matplotlib import pyplot as plt
import cv2
from skimage import metrics
from skimage.metrics import structural_similarity as ssim

def show(img):
    plt.imshow(img, cmap='gray')
    plt.xticks([])
    plt.yticks([])

def standard_median_filter(image, kernel_size=3):
    return cv2.medianBlur(image, kernel_size)

def adaptive_median_filter(image, max_kernel_size=7):
    h, w = image.shape
    new_img = np.copy(image)

    for i in range(h):
        for j in range(w):
            k = 3  # Start with 3x3 kernel
            while k <= max_kernel_size:
                i_min = max(i - k // 2, 0)
                i_max = min(i + k // 2 + 1, h)
                j_min = max(j - k // 2, 0)
                j_max = min(j + k // 2 + 1, w)

                region = image[i_min:i_max, j_min:j_max]
                z_min = np.min(region)
                z_max = np.max(region)
                z_med = np.median(region)
                z_xy = image[i, j]

                if z_min < z_med < z_max:
                    if z_min < z_xy < z_max:
                        new_img[i, j] = z_xy
                    else:
                        new_img[i, j] = z_med
                    break
                else:
                    k += 2  # Increase kernel size

    return new_img

def alpha_trimmed_mean_filter(image, kernel_size=3, d=2):
    h, w = image.shape
    pad_size = kernel_size // 2
    padded_img = np.pad(image, pad_size, mode='reflect')
    new_img = np.zeros_like(image)

    for i in range(h):
        for j in range(w):
            region = padded_img[i:i+kernel_size, j:j+kernel_size].flatten()
            sorted_region = np.sort(region)
            trimmed_region = sorted_region[d//2 : -d//2] if d < kernel_size**2 else sorted_region
            new_img[i, j] = np.mean(trimmed_region)

    return new_img.astype(np.uint8)

# Load and display original image
img_original = cv2.imread('sunflower.png', 0)
plt.figure(figsize=(10, 5))
plt.subplot(141), plt.title("Original"), show(img_original)

# Apply filters
median_filtered = standard_median_filter(img_original)
adaptive_filtered = adaptive_median_filter(img_original)
alpha_trimmed_filtered = alpha_trimmed_mean_filter(img_original, kernel_size=3, d=2)

# Display results
plt.subplot(142), plt.title("Standard Median Filter"), show(median_filtered)
plt.subplot(143), plt.title("Adaptive Median Filter"), show(adaptive_filtered)
plt.subplot(144), plt.title("Alpha-Trimmed Mean Filter"), show(alpha_trimmed_filtered)
plt.show()

# Compute and display quality metrics for different filters
def compute_metrics(original, filtered, name):
    mse = metrics.mean_squared_error(original, filtered)
    psnr = metrics.peak_signal_noise_ratio(original, filtered)
    ssim_value = ssim(original, filtered, data_range=original.max() - original.min())
    print(f"{name} - MSE: {mse:.4f}, PSNR: {psnr:.2f} dB, SSIM: {ssim_value:.4f}")

compute_metrics(img_original, median_filtered, "Standard Median Filter")
compute_metrics(img_original, adaptive_filtered, "Adaptive Median Filter")
compute_metrics(img_original, alpha_trimmed_filtered, "Alpha-Trimmed Mean Filter")