# -*- coding: utf-8 -*-
"""Paule_CSIS324LA_Region Analysis and Contour Following

Automatically generated by Colab.

AUTHOR: Faith Paule
PROGRAM: BCS35
COURSE: CSIS324LA (Finals)
DUE DATE: May 8, 10:59 am

ACTIVITY: EA - Image Segmentation Laboratory Activity (50 points)
MODULE 8 – Region Analysis and Contour Following

TOPIC: Computer Vision / Image Processing - Contour Detection, Shape Analysis, Moment Calculation
IDENTIFICATION:You are performing Region Analysis and Contour Following as part of an image processing laboratory activity. The tasks involve detecting, analyzing, and visualizing contours (object boundaries) in images using techniques like:
- Largest Contour Detection - Finding and highlighting the biggest shape in an image
- Contour Following with Centroids - Detecting all contours, computing their centers of mass (centroids), and linking them to simulate a path

Language & Tech Stack
Programming Language: Python 3

Tech Stack:
- OpenCV (cv2): For image I/O, contour detection (findContours), drawing, moment calculation (cv2.moments), and contour approximation (approxPolyDP)
- NumPy: For array operations
- Google Colab: The environment, with cv2_imshow for image display
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow
import os


# ============================================================================
# TASK 1: LARGEST CONTOUR DETECTION
# ============================================================================
"""
Goal: Find and highlight the largest contour in an image.
Output: Green outline of the contour + blue dots marking simplified key points.
"""

# Load and validate image
image_path = 'volleyball.png'
if os.path.exists(image_path):
    image = cv2.imread(image_path)
    if image is not None:
        # Convert to grayscale (contours work on single-channel images)
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

        # Binary threshold: pixels > 127 become white, rest become black
        _, thresh = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY)

        # Find all external contours (RETR_EXTERNAL) with simplified points
        contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

        # Sort contours by area (largest first)
        contours = sorted(contours, key=cv2.contourArea, reverse=True)

        if contours:
            largest_contour = contours[0]

            # Draw the contour in green (0,255,0) with thickness 2
            contour_img = image.copy()
            cv2.drawContours(contour_img, [largest_contour], -1, (0, 255, 0), 2)

            # Approximate contour to reduce number of points (1% of arc length)
            epsilon = 0.01 * cv2.arcLength(largest_contour, True)
            approx = cv2.approxPolyDP(largest_contour, epsilon, True)

            # Mark simplified points with blue dots
            for point in approx:
                cv2.circle(contour_img, tuple(point[0]), 4, (255, 0, 0), -1)

            # Display result
            cv2_imshow(contour_img)
            cv2.waitKey(0)
            cv2.destroyAllWindows()
        else:
            print("No contours found.")
    else:
        print(f"Error: Could not open or find the image at '{image_path}'")
else:
    print(f"Error: The file '{image_path}' does not exist.")


# ============================================================================
# TASK 2: CONTOUR FOLLOWING WITH CENTROIDS
# ============================================================================
"""
Goal: Detect all contours, compute their centroids (centers of mass),
      and draw a path connecting them.
Output: Green contours + Red centroid dots + Blue connecting lines (path)
"""

# Load the image
image = cv2.imread('volleyball.png')
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Binary threshold (pixels > 100 become white)
_, thresh = cv2.threshold(gray, 100, 255, cv2.THRESH_BINARY)

# Find all external contours
contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

# Create output image copy
output = image.copy()
centroids = []  # Store (x, y) coordinates of each contour's centroid

# Process each contour
for cnt in contours:
    # Draw contour in green
    cv2.drawContours(output, [cnt], -1, (0, 255, 0), 2)

    # Calculate centroid using image moments
    M = cv2.moments(cnt)
    if M["m00"] != 0:  # Avoid division by zero
        cx = int(M["m10"] / M["m00"])  # X coordinate
        cy = int(M["m01"] / M["m00"])  # Y coordinate
        centroids.append((cx, cy))
        cv2.circle(output, (cx, cy), 4, (0, 0, 255), -1)  # Red dot

# Connect centroids with a blue line to simulate "following" the path
for i in range(1, len(centroids)):
    cv2.line(output, centroids[i - 1], centroids[i], (255, 0, 0), 2)

# Display result
cv2_imshow(output)
cv2.waitKey(0)
cv2.destroyAllWindows()
